### ISSUE TITLE
kmod-usb-serial-ftdi should be a dependency for Domoticz

### ISSUE THREAD

**Issue by llhotka** [CZ-NIC/domoticz-turris-gadgets#1]
Domoticz requires *kmod-usb-serial-ftdi* package to be installed, so the latter should be listed as a dependency for *domoticz* package.

**Comment by sairon** [comment]
Adding this as a dependency of the package itself would be conceptually wrong (bloat when pkg is installed; it is runtime dependency only with certain configuration, etc...), but it totally makes sense to add it to the list of packages that are installed by the updater when "home automation" list is selected. We'll resolve it on that level. Thanks for the report.
