### ISSUE TITLE
Error message: Problem sending notification, please check the API key!

### ISSUE THREAD

**Issue by standus** [CZ-NIC/domoticz-turris-gadgets#2]
I would like to use Email notification over email setting from gmail, but always I got this message.
I tried many setting variants.
I tried localhost with same result.

Is it issue or exists any way how to enable send notification email over Turris?

**Comment by pspirek** [comment]
This is an issue specific to Turris build of Domoticz. Currently, there is a workaround with "Custom" notification, which runs an external mailing script. It is described on Turris forum here: https://www.turris.cz/forum/topic_show.pl?tid=874
